// Builds pages.js from the client URL sheet (urls.csv): live URL, DA path, language, translation group, scope.
// node tools/importer/build-pages.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import daPath from './paths.js';

const rows = readFileSync(new URL('./urls.csv', import.meta.url), 'utf8').trim().split(/\r?\n/).slice(1)
  .map((line) => line.split(','))
  .filter(([, , , url]) => url?.startsWith('http'));

let group = 0;
const pages = rows.map(([pageGroup, name, lang, url, note = '']) => {
  if (lang === 'EN') group += 1;
  return {
    lang, url: url.split('#')[0], path: daPath(url), group, section: pageGroup, name, outOfScope: /no longer in scope/i.test(note),
  };
});
writeFileSync(new URL('./pages.js', import.meta.url), `// generated by build-pages.mjs\nexport default ${JSON.stringify(pages, null, 1)};\n`);
console.log(`${pages.length} pages, ${group} translation groups`);
