// Builds icons.js: live SVG URL -> DA icon name, by comparing normalised SVG markup with content/icons.
// node tools/importer/build-icons.mjs <cached live html dir>
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const LIVE = 'https://www.rbcroyalbank.com';
const ICONS = new URL('../../content/icons/', import.meta.url).pathname;
const dir = process.argv[2] || '/tmp/rbc-import-cache';

const norm = (svg) => svg
  .replace(/<\?xml[^>]*>|<!--[\s\S]*?-->|<title>[\s\S]*?<\/title>|<desc>[\s\S]*?<\/desc>/g, '')
  .replace(/\s(id|class|data-name|xmlns(:\w+)?|version|style|width|height)="[^"]*"/g, '')
  .replace(/\s+/g, '')
  .toLowerCase();
const paths = (svg) => (norm(svg).match(/\sd="[^"]*"|d="[^"]*"/g) || []).join('');

const da = readdirSync(ICONS).filter((f) => f.endsWith('.svg')).map((f) => {
  const svg = readFileSync(join(ICONS, f), 'utf8');
  return { name: f.replace(/\.svg$/, ''), norm: norm(svg), paths: paths(svg) };
});

const srcs = new Set();
readdirSync(dir).filter((f) => f.endsWith('.html')).forEach((f) => {
  const html = readFileSync(join(dir, f), 'utf8');
  [...html.matchAll(/<img[^>]*\ssrc=["']([^"']+\.svg)["']/g)].forEach(([, src]) => srcs.add(new URL(src, LIVE).href));
});

const map = {};
let unmatched = 0;
for (const src of [...srcs].sort()) {
  const res = await fetch(src);
  if (!res.ok) { unmatched += 1; continue; }
  const svg = await res.text();
  const n = norm(svg);
  const p = paths(svg);
  const hit = da.find((d) => d.norm === n) || (p && da.find((d) => d.paths === p));
  if (hit) map[src] = hit.name; else unmatched += 1;
}
writeFileSync(new URL('./icons.js', import.meta.url), `// generated by build-icons.mjs\nexport default ${JSON.stringify(map, null, 2)};\n`);
console.log(`${Object.keys(map).length} matched, ${unmatched} unmatched of ${srcs.size} live SVGs`);
